### ISSUE TITLE
Allow specifying separate upload bucket

### ISSUE THREAD

**Issue by nanaya** [feedbin/image#15]
Using minio storage and shared env with main feedbin installation, both file uploads (subscription opml) and the images end up in same bucket with one in `uploads` directory and the other directly in the top directory.

Would you accept PR adding support for separate bucket for image uploads similar to `AWS_S3_BUCKET_FAVICONS`?

(there's also issue minio doesn't support per-object permission but that's rather irrelevant overall)

(I'm not going as far as adding migration support though)

**Comment by benubois** [comment]
Sure!
